var events = {
	
	NEW_USER_ADDING : 'NEW_USER_ADDING',
	REGISTRATION_FAILED : 'REGISTRATION_FAILED', 
	USER_REGISTERED : 'USER_SUCCESSFULLY_REGISTERED',
	LOGIN_ATTEMPT : 'LOGIN',
	LOGIN_FAILED : 'LOGIN_FAILED',
	LOGIN_SUCCESSFULL : 'USER_LOGGED_IN',
	NEW_CHAT_CREATING: 'NEW_CHAT_CREATING',
	CHAT_CREATION_FAILED : 'CHAT_CREATION_FAILED',
	CHAT_CREATED: 'CHAT_CREATED',
	JOINING_CHAT : 'JOIN_CHAT',
	USER_JOINING_FAILED : 'USER_JOINING_FAILED',
	USER_JOINED: 'ON_USER_JOINED',
	ADDING_NEW_MESSAGE: 'ON_MESSAGE_ADDED',
	MESSAGE_ADDING_FAILED: 'MESSAGE_ADDING_FAILED',
	MESSAGE_ADDED: 'MESSAGE_ADDED',
	LEAVING_CHAT: 'LEAVING_CHAT',
	USER_LEAVING_FAILED : 'USER_LEAVING_FAILED',
	CHAT_LEAVED: 'CHAT_LEAVED'
}

if (typeof define !== 'function') {
    var define = require('amdefine')(module);
}

define(function() {
	return events;
});